DROP TABLE IF EXISTS secrets;
DROP TABLE IF EXISTS task_logs;
DROP TABLE IF EXISTS task_runs;
DROP TABLE IF EXISTS job_runs;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS users;
