// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountLogsByJobRun(ctx context.Context, jobRunID pgtype.UUID) (int64, error)
	CountLogsByTaskRun(ctx context.Context, taskRunID pgtype.UUID) (int64, error)
	CountLogsByType(ctx context.Context, type_ string) (int64, error)
	CreateBulkTasks(ctx context.Context, arg CreateBulkTasksParams) ([]CreateBulkTasksRow, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (CreateJobRow, error)
	CreateJobLog(ctx context.Context, arg CreateJobLogParams) error
	CreateJobRun(ctx context.Context, arg CreateJobRunParams) (CreateJobRunRow, error)
	CreateLog(ctx context.Context, arg CreateLogParams) error
	CreateSecret(ctx context.Context, arg CreateSecretParams) (CreateSecretRow, error)
	CreateSystemLog(ctx context.Context, arg CreateSystemLogParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateTaskLog(ctx context.Context, arg CreateTaskLogParams) error
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (CreateTaskRunRow, error)
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteJobRun(ctx context.Context, id pgtype.UUID) error
	DeleteLog(ctx context.Context, id int64) error
	DeleteLogsByJobRun(ctx context.Context, jobRunID pgtype.UUID) error
	DeleteLogsByTaskRun(ctx context.Context, taskRunID pgtype.UUID) error
	DeleteLogsByType(ctx context.Context, type_ string) error
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteTaskRun(ctx context.Context, id pgtype.UUID) error
	GetJob(ctx context.Context, id pgtype.UUID) (GetJobRow, error)
	GetJobRun(ctx context.Context, id pgtype.UUID) (GetJobRunRow, error)
	GetJobWithTasks(ctx context.Context, id pgtype.UUID) (GetJobWithTasksRow, error)
	GetLog(ctx context.Context, id int64) (Log, error)
	GetSecret(ctx context.Context, arg GetSecretParams) (GetSecretRow, error)
	GetSecretByName(ctx context.Context, arg GetSecretByNameParams) (GetSecretByNameRow, error)
	GetTask(ctx context.Context, id pgtype.UUID) (GetTaskRow, error)
	GetTaskRun(ctx context.Context, id pgtype.UUID) (GetTaskRunRow, error)
	GetTaskRunByJobRunAndTaskID(ctx context.Context, arg GetTaskRunByJobRunAndTaskIDParams) (GetTaskRunByJobRunAndTaskIDRow, error)
	GetTasksByJobID(ctx context.Context, jobID pgtype.UUID) ([]GetTasksByJobIDRow, error)
	JobRunsWithTasks(ctx context.Context, id pgtype.UUID) (JobRunsWithTasksRow, error)
	ListJobRuns(ctx context.Context, jobID pgtype.UUID) ([]ListJobRunsRow, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error)
	ListLogs(ctx context.Context, arg ListLogsParams) ([]Log, error)
	ListLogsByJobRun(ctx context.Context, jobRunID pgtype.UUID) ([]Log, error)
	ListLogsByJobRunAndLevel(ctx context.Context, arg ListLogsByJobRunAndLevelParams) ([]Log, error)
	ListLogsByJobRunPaginated(ctx context.Context, arg ListLogsByJobRunPaginatedParams) ([]Log, error)
	ListLogsByLevel(ctx context.Context, arg ListLogsByLevelParams) ([]Log, error)
	ListLogsByTaskRun(ctx context.Context, taskRunID pgtype.UUID) ([]Log, error)
	ListLogsByType(ctx context.Context, arg ListLogsByTypeParams) ([]Log, error)
	ListPendingJobRuns(ctx context.Context) ([]ListPendingJobRunsRow, error)
	ListSecrets(ctx context.Context, userID pgtype.UUID) ([]ListSecretsRow, error)
	ListSystemLogs(ctx context.Context, arg ListSystemLogsParams) ([]Log, error)
	ListTaskRuns(ctx context.Context, jobRunID pgtype.UUID) ([]ListTaskRunsRow, error)
	ListTaskRunsByJob(ctx context.Context, id pgtype.UUID) ([]ListTaskRunsByJobRow, error)
	ListTasks(ctx context.Context, jobID pgtype.UUID) ([]ListTasksRow, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) error
	UpdateJobRun(ctx context.Context, arg UpdateJobRunParams) error
	UpdateJobRunError(ctx context.Context, arg UpdateJobRunErrorParams) error
	UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) error
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskRun(ctx context.Context, arg UpdateTaskRunParams) error
	UpdateTaskRunError(ctx context.Context, arg UpdateTaskRunErrorParams) error
	UpdateTaskRunOutput(ctx context.Context, arg UpdateTaskRunOutputParams) error
	UpdateTaskRunStatus(ctx context.Context, arg UpdateTaskRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
