// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBulkTasks(ctx context.Context, arg CreateBulkTasksParams) ([]CreateBulkTasksRow, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (CreateJobRow, error)
	CreateJobRun(ctx context.Context, arg CreateJobRunParams) (CreateJobRunRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (CreateTaskRunRow, error)
	DeleteJob(ctx context.Context, id pgtype.UUID) error
	DeleteJobRun(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteTaskRun(ctx context.Context, id pgtype.UUID) error
	GetJob(ctx context.Context, id pgtype.UUID) (GetJobRow, error)
	GetJobRun(ctx context.Context, id pgtype.UUID) (GetJobRunRow, error)
	GetJobWithTasks(ctx context.Context, id pgtype.UUID) (GetJobWithTasksRow, error)
	GetTask(ctx context.Context, id pgtype.UUID) (GetTaskRow, error)
	GetTaskRun(ctx context.Context, id pgtype.UUID) (GetTaskRunRow, error)
	GetTasksByJobID(ctx context.Context, jobID pgtype.UUID) ([]GetTasksByJobIDRow, error)
	JobRunsWithTasks(ctx context.Context, id pgtype.UUID) (JobRunsWithTasksRow, error)
	ListJobRuns(ctx context.Context, jobID pgtype.UUID) ([]ListJobRunsRow, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error)
	ListPendingJobRuns(ctx context.Context) ([]ListPendingJobRunsRow, error)
	ListTaskRuns(ctx context.Context, jobRunID pgtype.UUID) ([]ListTaskRunsRow, error)
	ListTaskRunsByJob(ctx context.Context, id pgtype.UUID) ([]ListTaskRunsByJobRow, error)
	ListTasks(ctx context.Context, jobID pgtype.UUID) ([]ListTasksRow, error)
	UpdateJob(ctx context.Context, arg UpdateJobParams) error
	UpdateJobRun(ctx context.Context, arg UpdateJobRunParams) error
	UpdateJobRunError(ctx context.Context, arg UpdateJobRunErrorParams) error
	UpdateJobRunStatus(ctx context.Context, arg UpdateJobRunStatusParams) error
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskRun(ctx context.Context, arg UpdateTaskRunParams) error
	UpdateTaskRunError(ctx context.Context, arg UpdateTaskRunErrorParams) error
	UpdateTaskRunStatus(ctx context.Context, arg UpdateTaskRunStatusParams) error
}

var _ Querier = (*Queries)(nil)
